name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: make_client
      run: cd client/ && make
    - name: make_server
      run: cd server/ && make
